  opentsdb:
    image: petergrace/opentsdb-docker:latest
    ports:
      - "4242:4242"

  fake-opentsdb-data:
    image: plutono/fake-data-gen
    network_mode: bridge
    environment:
      FD_DATASOURCE: opentsdb

